name: ci
on:
  push:
    branches: [ "master" ]  # Run only on master
  pull_request:             # and on PRs targeting master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - name: Install Zig
        run: |
          curl -s https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz | tar -xJ
          echo "$PWD/zig-linux-x86_64-0.14.0" >> $GITHUB_PATH
      - name: Check formatting
        run: zig fmt --ast-check .
      - name: Build
        run: zig build -Doptimize=ReleaseSafe --summary all
      - name: Run tests
        run: zig build test -Doptimize=ReleaseSafe --summary all
